[package]
name = "tts-script-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorize = "0.1.0"
regex = "1.6.0"
serde_json = "1.0"
snailquote = "0.3.1"
